<?php
$jsonflex = 
[
  "type"=>"flex",
  "altText"=>"Flex Message",
  "contents"=>[
    "type"=>"bubble",
    "direction"=>"ltr",
    "hero"=>[
      "type"=>"image",
      "url"=>"https://patkolpae.com/IOT_linebot/Images/vogticecubes.jpg",
      "size"=>"full",
      "aspectRatio"=>"1.91:1",
      "aspectMode"=>"cover",
      "action"=>[
        "type"=>"uri",
        "label"=>"Line",
        "uri"=>"https://linecorp.com/"
      ]
    ],
    "body"=>[
      "type"=>"box",
      "layout"=>"vertical",
      "contents"=>[
        [
          "type"=>"text",
          "text"=> "ข้อมูลของโรงน้ำแข็ง",
          "size"=>"xl",
          "gravity"=>"top",
          "weight"=>"bold"
        ],
        [
          "type"=>"box",
          "layout"=>"baseline",
          "margin"=>"md",
          "contents"=>[
            [
              "type"=>"text",
              "text"=>"เลือกโรงน้ำแข็งที่ต้องการ",
              "size"=>"md",
              "align"=>"start",
              "gravity"=>"top",
              "weight"=>"bold"
            ]
          ]
        ]
      ]
    ],
    "footer"=>[
      "type"=>"box",
      "layout"=>"vertical",
      "flex"=>0,
      "spacing"=>"sm",
      "contents"=>[
       
      ]
    ],
    "styles"=>[
      "hero"=>[
        "separatorColor"=>"#FFFFFF"
      ]
    ]
  ]
];

?>