<?php
$jsonflex =
[
    "type"=>"flex",
    "altText"=>"Flex Message",
    "contents"=>[
      "type"=>"bubble",
      "direction"=>"ltr",
    "hero"=>[
      "type"=>"image",
      "url"=>"https://scdn.line-apps.com/n/channel_devcenter/img/fx/01_5_carousel.png",
      "size"=>"full",
      "aspectRatio"=>"20:13",
      "aspectMode"=>"cover"
    ],
    "body"=>[
      "type"=>"box",
      "layout"=>"vertical",
      "spacing"=>"sm",
      "contents"=>[
        [
          "type"=>"text",
          "text"=>"Arm Chair, White",
          "weight"=>"bold",
          "size"=>"xl",
          "wrap"=>true,
          "contents"=>[]
        ],
        [
          "type"=>"box",
          "layout"=>"baseline",
          "contents"=>[
            [
              "type"=>"text",
              "text"=>"$49",
              "weight"=>"bold",
              "size"=>"xl",
              "flex"=>0,
              "wrap"=>true,
              "contents"=>[]
            ],
            [
              "type"=>"text",
              "text"=>".99",
              "weight"=>"bold",
              "size"=>"sm",
              "flex"=>0,
              "wrap"=>true,
              "contents"=>[]
            ]
          ]
        ]
      ]
    ],
    "footer"=>[
      "type"=>"box",
      "layout"=>"vertical",
      "spacing"=>"sm",
      "contents"=>[
        [
          "type"=>"button",
          "action"=>[
            "type"=>"uri",
            "label"=>"Add to Cart",
            "uri"=>"https://linecorp.com"
          ],
          "style"=>"primary"
        ],
        [
          "type"=>"button",
          "action"=>[
            "type"=>"uri",
            "label"=>"Add to wishlist",
            "uri"=>"https://linecorp.com"
          ]
        ]
      ]
    ]
    ]
          ];
