window.onload = function () {
    const defaultLiffId = "1623482821-1py6QaL6";
    let myLiffId = "1623482821-1py6QaL6";

    myLiffId = defaultLiffId;
    initializeLiffOrDie(myLiffId);
};

/**
* Check if myLiffId is null. If null do not initiate liff.
* @param {string} myLiffId The LIFF ID of the selected element
*/
function initializeLiffOrDie(myLiffId) {
    if (!myLiffId) {
        document.getElementById("liffAppContent").classList.add('hidden');
        document.getElementById("liffIdErrorMessage").classList.remove('hidden');
    } else {
        initializeLiff(myLiffId);
    }
}

/**
* Initialize LIFF
* @param {string} myLiffId The LIFF ID of the selected element
*/
function initializeLiff(myLiffId) {
    liff
        .init({
            liffId: myLiffId
        })
        .then(() => {
            // start to use LIFF's api
            initializeApp();
            
        })
        .catch((err) => {
            document.getElementById("liffAppContent").classList.add('hidden');
            document.getElementById("liffInitErrorMessage").classList.remove('hidden');
        });
}

/**
 * Initialize the app by calling functions handling individual app components
 */
function initializeApp() {

    //displayLiffData();
    //displayIsInClientInfo();
    registerButtonHandlers();

    // check if the user is logged in/out, and disable inappropriate button
    //if (liff.isLoggedIn()) {
    //    document.getElementById('liffLoginButton').disabled = true;
    //} else {
    //    document.getElementById('liffLogoutButton').disabled = true;
    //}
}

/**
* Display data generated by invoking LIFF methods
*/
function displayLiffData() {
    //document.getElementById('browserLanguage').textContent = liff.getLanguage();
    //document.getElementById('sdkVersion').textContent = liff.getVersion();
    //document.getElementById('isInClient').textContent = liff.isInClient();
    //document.getElementById('isLoggedIn').textContent = liff.isLoggedIn();
    //document.getElementById('deviceOS').textContent = liff.getOS();
}

/**
* Toggle the login/logout buttons based on the isInClient status, and display a message accordingly
*/
function displayIsInClientInfo() {
    //if (liff.isInClient()) {
    //    document.getElementById('liffLoginButton').classList.toggle('hidden');
    //    document.getElementById('liffLogoutButton').classList.toggle('hidden');
    //    document.getElementById('isInClientMessage').textContent = 'You are opening the app in the in-app browser of LINE.';
    //} else {
    //    document.getElementById('isInClientMessage').textContent = 'You are opening the app in an external browser.';
    //}
}

/**
* Register event handlers for the buttons displayed in the app
*/
function registerButtonHandlers() {
    // openWindow call
    liff.getProfile().then(function (profile) {
        document.getElementById('LineTokenLine').value = profile.userId;
        document.getElementById('DisplayNameLine').value = profile.displayName;

        const profilePictureDiv = document.getElementById('PictureLine');
        //if (profilePictureDiv.firstElementChild) {
        //    profilePictureDiv.removeChild(profilePictureDiv.firstElementChild);
        //}
        profilePictureDiv.src = profile.pictureUrl;

    }).catch(function (error) {
        window.alert('Error getting profile: ' + error);
    });
}

/**
* Alert the user if LIFF is opened in an external browser and unavailable buttons are tapped
*/
function sendAlertIfNotInClient() {
    alert('This button is unavailable as LIFF is currently being opened in an external browser.');
}

/**
* Toggle access token data field
*/
function toggleAccessToken() {
    toggleElement('accessTokenData');
}

/**
* Toggle profile info field
*/
function toggleProfileData() {
    toggleElement('profileInfo');
}

/**
* Toggle scanCode result field
*/
function toggleQrCodeReader() {
    toggleElement('scanQr');
}

/**
* Toggle specified element
* @param {string} elementId The ID of the selected element
*/
function toggleElement(elementId) {
    const elem = document.getElementById(elementId);
    if (elem.offsetWidth > 0 && elem.offsetHeight > 0) {
        elem.style.display = 'none';
    } else {
        elem.style.display = 'block';
    }
}